---

# NOTE(sheeprine): the deb parameter from apt is broken as it doesn't
# follow redirects. I also doesn't detect the real filename creating huge
# file based on splited url which makes the install fail (as the filename is
# too long). So we go back to the basics
- name: Debian | Install package from github release
  include_tasks: "install.yml"
  vars:
    pkg_extension: ".deb"
    pkg_install_tasks: "_deb.yml"
  when: ansible_os_family == "Debian"
