---

- name: Download release page
  uri:
    url: "{{ pkg_url }}/releases/latest"
    follow_redirects: true
    return_content: true
  register: release_page
  changed_when: false
  check_mode: false

  # TODO(sheeprine): Fail and show a message when no deb package is found
  # on the release page.
- name: Find application package url
  set_fact:
    final_pkg_url: >-
      {{ release_page.content |
      regex_search('".*/releases/download/.*' + pkg_extension + '"') |
      regex_replace('"', '') |
      regex_replace('^', 'https://github.com') }}
  changed_when: false
