---
- include_tasks: ranger.yml

- name: "OSX | Install tmux"
  when: ansible_os_family == "Darwin"
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - reattach-to-user-namespace
    - tmux

- name: "Linux | Install tmux"
  when: ansible_system == "Linux"
  become: true
  package:
    name:
      - xsel
      - tmux
    state: present

- name: "OSX | Install gopass as a passwordstore alternative"
  homebrew:
    name: "gopass"
    state: present
  when: ansible_os_family == "Darwin"

- name: "Debian | Install gopass as a passwordstore alternative"
  include_tasks: "../../_pkg_install/tasks/debian.yml"
  vars:
    pkg_url: "{{ gopass_deb_pkg }}"
  when: ansible_os_family == "Debian"

- name: "Arch Linux | Install gopass as a passwordstore alternative"
  become: true
  package:
    name: "gopass"
    state: present
  when: ansible_os_family == "Archlinux"

# FIXME(sheeprine): Do more than copying tmux configuration
- name: Copy tmux configuration
  copy:
    src: "tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
