---
- include_tasks: ranger.yml

- name: OSX | Install tmux
  when: ansible_os_family == "Darwin"
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - reattach-to-user-namespace
    - tmux

- name: Debian | Install tmux
  when: ansible_os_family == "Debian"
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - xsel
    - tmux

- name: "OSX | Install gopass as a passwordstore alternative"
  homebrew:
    name: "gopass"
    state: present
  when: ansible_os_family == "Darwin"

- name: "Debian | Install gopass as a passwordstore alternative"
  include_tasks: "../../_pkg_install/tasks/debian.yml"
  vars:
    pkg_url: "{{ gopass_deb_pkg }}"
  when: ansible_os_family == "Debian"

# FIXME(sheeprine): Do more than copying tmux configuration
- name: Copy tmux configuration
  copy:
    src: "tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
