---
- include_tasks: ranger.yml

  # FIXME(sheeprine): Do more than copying tmux configuration
- name: Copy tmux configuration
  copy:
    src: "tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
