---
- name: Debian | Install ranger
  become: true
  apt:
    name: "{{ ranger_debian_packages }}"
    state: present
  when: ansible_os_family == "Debian"

- name: OSX | Install ranger
  homebrew:
    name: "{{ ranger_osx_packages }}"
    state: present
  when: ansible_os_family == "Darwin"

- name: Create ranger config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/ranger/"
    state: directory

- name: Install custom ranger configuration file
  template:
    src: ranger/rc.conf.j2
    dest: "{{ ansible_env.HOME }}/.config/ranger/rc.conf"
  vars:
    preview_images: "{{ not (ansible_os_family == 'Darwin') }}"

- name: Copy ranger default scope and rile configuration
  command: "ranger --copy-config={{ item }}"
  loop:
  - scope
  - rifle
  when: not ansible_check_mode
