---
- name: Debian | Install ranger
  become: true
  apt:
    name: "{{ ranger_debian_packages }}"
    state: present
  when: ansible_os_family == "Debian"

- name: OSX | Install ranger
  homebrew:
    name: "{{ ranger_osx_packages }}"
    state: present
  when: ansible_os_family == "Darwin"

- name: Create ranger config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/ranger/"
    state: directory

- name: Install custom ranger configuration file
  template:
    src: ranger/rc.conf.j2
    dest: "{{ ansible_env.HOME }}/.config/ranger/rc.conf"
  vars:
    preview_images: "{{ not (ansible_os_family == 'Darwin') }}"

- name: Deploy ranger default scope and rile configuration
  when: not ansible_check_mode
  block:
  - name: Create temporary directory to store new conf files
    tempfile:
      state: directory
    register: ranger_temp
    changed_when: no
  - name: Copy ranger files to temporary directory
    command: "ranger -r {{ ranger_temp.path }} --copy-config={{ item }}"
    loop:
    - scope
    - rifle
    changed_when: no
  - name: Copy ranger configuration files if newer
    copy:
      src: "{{ ranger_temp.path }}/{{ item }}"
      dest: "{{ ansible_env.HOME }}/.config/ranger/"
      remote_src: yes
    loop:
    - scope.sh
    - rifle.conf
  - name: "Ensure ranger scope.sh is executable"
    file:
      path: "{{ ansible_env.HOME }}/.config/ranger/scope.sh"
      mode: "0755"

  always:
  - name: Delete ranger temporary directory
    file:
      path: "{{ ranger_temp.path }}"
      state: absent
    changed_when: no
