---
- name: Debian | Install ranger
  apt:
    name: "{{ item }}"
    state: present
  loop:
  - ranger
  - atool
  - caca-utils
  - w3m-img
  - highlight
  - poppler-utils
  when: ansible_os_family == "Debian"

- name: OSX | Install ranger
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
  - ranger
  - atool
  - highlight
  - poppler
  when: ansible_os_family == "Darwin"

- name: Install custom ranger configuration file
  template:
    src: ranger/rc.conf.j2
    dest: "{{ ansible_env.HOME }}/.config/ranger/rc.conf"
  vars:
    preview_images: "{{ not (ansible_os_family == 'Darwin') }}"

- name: Copy ranger default scope and rile configuration
  command: "ranger --copy-config={{ item }}"
  loop:
  - scope
  - rifle
  when: not ansible_check_mode
