---
preview_images: true
ranger_debian_packages:
  - ranger
  - atool
  - caca-utils
  - w3m-img
  - highlight
  - poppler-utils
ranger_arch_packages:
  - ranger
  - atool
  - libcaca
  - mediainfo
  - w3m
  - highlight
  - poppler
ranger_osx_packages:
  - ranger
  - atool
  - highlight
  - poppler
gopass_deb_pkg: "https://github.com/gopasspw/gopass"
bat_theme: "gruvbox-dark"
