---
- name: Install/update zsh
  become: true
  apt:
    name: zsh
    state: latest

- name: Install zplug dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  loop:
  - curl
  - gawk
  - git
