---
- name: Install zsh
  become: true
  apt:
    name: zsh
    state: present

- name: Install zplug dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
  - curl
  - gawk
  - git
