---
- name: Install zsh
  become: true
  package:
    name: zsh
    state: present

- name: Install zplugin dependencies
  become: true
  package:
    name: "{{ zplugin_dependencies }}"
    state: present

- name: Install fzf from sources
  git:
    repo: "https://github.com/junegunn/fzf.git"
    version: master
    depth: 1
    dest: "{{ ansible_env.HOME }}/.fzf"
  register: fzf_repo

- name: Install fzf binaries and scripts
  command: >
    {{ ansible_env.HOME }}/.fzf/install
    --key-bindings --completion --no-update-rc --no-bash --no-fish
  args:
    creates: '{{ fzf_repo is changed|ternary(omit, ansible_env.HOME + "/.fzf.zsh") }}'
