---
- include_tasks: osx.yml
  when: ansible_os_family == "Darwin"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Remove old zplug install
  file:
    path: "{{ ansible_env.HOME }}/.zplug"
    state: absent

- name: Install zplugin from sources
  shell: curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh| zsh
  args:
    creates: "{{ ansible_env.HOME }}/.zplugin"
    warn: false

- name: Create zsh config files
  copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"

- name: Detect zsh path
  command: which zsh
  register: zsh_path
  changed_when: false
  check_mode: no

- name: Add zsh to allowed shells
  become: yes
  lineinfile:
    path: /etc/shells
    regexp: "^{{ zsh_path.stdout }}$"
    line: "{{ zsh_path.stdout }}"

- name: Set zsh as default shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path.stdout }}"
