---
- name: Install zsh
  homebrew:
    name: zsh
    state: present

- name: Install zinit dependencies
  homebrew:
    name: "{{ zinit_dependencies }} + ['fzf']"
    state: present

# TODO(sheeprine): This is sloppy as it's run every time
- name: Install fzf binaries and scripts
  shell: >
    $(brew --prefix)/opt/fzf/install
    --key-bindings --completion --no-update-rc --no-bash --no-fish
  args:
    creates: "{{ ansible_env['HOME'] }}/.zsh.fzf"
  changed_when: no
  when: not ansible_check_mode
