---
- name: Install zsh
  homebrew:
    name: zsh
    state: present

- name: Install zplugin dependencies
  homebrew:
    name: "{{ zplugin_dependencies }} + ['fzf']"
    state: present

  # TODO(sheeprine): This is sloppy as it's run every time
- name: Install fzf binaries and scripts
  command: "/usr/local/opt/fzf/install --key-bindings --completion --no-update-rc --no-bash --no-fish"
  changed_when: no
  when: not ansible_check_mode
