# Load zplugin
source "$HOME/.zplugin/bin/zplugin.zsh"
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin

# Git
zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/git/git.plugin.zsh
zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/gitignore/gitignore.plugin.zsh

# SSH/GPG Agent
zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/ssh-agent/ssh-agent.plugin.zsh
zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/gpg-agent/gpg-agent.plugin.zsh

zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/taskwarrior/taskwarrior.plugin.zsh
zplugin ice wait"0" lucid
zplugin snippet OMZ::plugins/golang/golang.plugin.zsh

if [[ $OSTYPE == darwin* ]]; then
  zplugin ice wait"0" lucid
  zplugin snippet OMZ::plugins/osx/osx.plugin.zsh
fi

# Theme
zplugin ice pick"async.zsh" src"pure.zsh" compile"(pure|async).zsh"
zplugin light sindresorhus/pure

autoload -U compinit && compinit

# ESC+BKSPC stop at non alphanumerical (bash style)
autoload -U select-word-style
select-word-style bash

# History
HISTFILE=$HOME/.zsh_history
HISTSIZE=12000
SAVEHIST=10000
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history

bindkey -e

# Load fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Locales
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

export BROWSER=open
export EDITOR=nvim
export VISUAL=$EDITOR
export GIT_EDITOR=$EDITOR

# Paths
export GOPATH="$HOME/.go"
export PATH="$GOPATH/bin:$PATH"
if [[ $OSTYPE == darwin* ]]; then
  # Override default macOS python2 install
  export PATH="/usr/local/opt/python@2/bin:$PATH"
fi
export PATH="$HOME/.local/bin:$PATH"

# Lazy alias
alias vim='nvim'
