source $HOME/.zplug/init.zsh

# Git
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/gitignore", from:oh-my-zsh

# SSH/GPG Agent
zplug "plugins/ssh-agent", from:oh-my-zsh
zplug "plugins/gpg-agent", from:oh-my-zsh

zplug "plugins/taskwarrior", from:oh-my-zsh
zplug "plugins/golang", from:oh-my-zsh

if [[ $OSTYPE == darwin* ]]; then
  zplug "plugins/osx", from:oh-my-zsh
  zplug '/usr/local/opt/fzf/shell', from:local
else
  zplug '~/.fzf', from:local
fi

# Async exec, required by theme
zplug mafredri/zsh-async, from:github
# Theme
zplug sindresorhus/pure, use:pure.zsh, from:github, as:theme

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load

autoload -U compinit && compinit

# ESC+BKSPC stop at non alphanumerical (bash style)
autoload -U select-word-style
select-word-style bash

# History
HISTFILE=$HOME/.zsh_history
HISTSIZE=12000
SAVEHIST=10000
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history

bindkey -e

# Locales
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

export BROWSER=open
export VISUAL=vimr
export EDITOR=nvim
export GIT_EDITOR=$EDITOR

# Paths
export GOPATH="$HOME/.go"
export PATH="$GOPATH/bin:$PATH"

# Lazy alias
alias vim='nvim'
