---
- name: Include OSX related tasks
  include_tasks: osx.yml
  when: ansible_os_family == "Darwin"

- name: Include Debian related tasks
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Include shell related tasks
  include_tasks: shell.yml
  tags:
    - shell
