---
- name: Create nvim config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim/"
    state: directory

- name: Create nvim default plugin directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
    state: directory

- name: Copy nvim configuration
  copy:
    src: "nvim/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/nvim/"
  with_items:
    - init.vim
    - plugins.vim

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
