---
- name: Debian | Install desktop environment
  become: true
  package:
    name:
      - i3
      - lightdm
      - autorandr
      - arandr
      - unclutter
      - feh
    state: latest
  when: ansible_os_family == "Debian"

- name: Arch Linux | Install desktop environment
  become: true
  package:
    name:
      - xorg
      - mesa
      - lightdm
      - lightdm-webkit-theme-litarvan
      - pulseaudio
      - i3
      - autorandr
      - arandr
      - unclutter
      - feh
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - libva-intel-driver
      - pacman-contrib
      - firefox
    state: latest
  when: ansible_os_family == "Archlinux"

- name: "Install rofi related config and packages"
  import_tasks: "rofi.yml"
  when: use_rofi

- name: Install j4 dmenu replacement
  become: true
  package:
    name: "j4-dmenu-desktop"
    state: latest
  when:
    - use_j4
    - not use_rofi
    - ansible_os_family == "Debian"

- name: Create i3 configuration directory
  file:
    path: "{{ ansible_env.HOME }}/.config/i3"
    state: directory

- name: Copy i3 configuration file
  template:
    src: "config.j2"
    dest: "{{ ansible_env.HOME }}/.config/i3/config"

- name: Set i3 as lightdm default session
  become: true
  copy:
    src: "i3.conf"
    dest: "/etc/lightdm/lightdm.conf.d/"
    owner: "root"
    group: "root"
    mode: 0644

- name: "Enable lightdm"
  become: true
  systemd:
    name: "lightdm"
    enabled: true

- name: "Set lightdm as default DM"
  become: true
  debconf:
    name: "lightdm"
    question: "shared/default-x-display-manager"
    vtype: "select"
    value: "lightdm"
  when: ansible_os_family == "Debian"

- name: "Set keyboard layout"
  become: true
  template:
    src: "keyboard.j2"
    dest: "/etc/default/keyboard"
  notify: "reconfigure keyboard"
  when: ansible_os_family == "Debian"
