---
nvim_venv_dir: "{{ ansible_env.HOME }}/.local/share/nvim/pyvenv"
nvim_default_colorscheme: "NeoSolarized"
ripgrep_deb_pkg: "https://github.com/BurntSushi/ripgrep/releases/download/0.10.0/ripgrep_0.10.0_amd64.deb"
nvim_debian_dependencies:
- git
- golang
- python-pip
- python-virtualenv
- python-setuptools
- python-dev
- python3-pip
- python3-virtualenv
- python3-setuptools
- python3-dev
nvim_osx_dependencies:
- git
- golang
- python-setuptools
- python3-setuptools
- python3-dev
- fzf
- ripgrep
