---
nvim_venv_dir: "{{ ansible_env.HOME }}/.local/share/nvim/pyvenv"
nvim_debian_dependencies:
- git
- golang
- python-pip
- python-virtualenv
- python-setuptools
- python-dev
- python3-pip
- python3-virtualenv
- python3-setuptools
- python3-dev
nvim_osx_dependencies:
- git
- golang
- python-setuptools
- python3-setuptools
- python3-dev
- fzf
