---
- name: Install neovim
  become: true
  package:
    name: neovim
    state: present

- name: Install neovim plugins dependencies
  become: true
  package:
    name: "{{ nvim_arch_dependencies }}"
    state: present
