---
- name: Install neovim
  become: true
  package:
    name: neovim
    state: present
  when: false

- name: Install neovim appimage
  include_tasks: "appimage.yml"

- name: Install neovim plugins dependencies
  become: true
  package:
    name: "{{ nvim_arch_dependencies }}"
    state: present
