---
- name: Add neovim PPA for Ubuntu
  become: true
  apt_repository:
    repo: "ppa:neovim-ppa/stable"
  register: neovim_ppa
  when: ansible_distribution == "Ubuntu"

- name: Update package list to reflect PPA change
  become: true
  apt:
    update_cache: true
  when:
    - ansible_distribution == "Ubuntu"
    - neovim_ppa is changed

- name: Debian | Install ripgrep from github release
  include_tasks: "../../_pkg_install/tasks/debian.yml"
  vars:
    pkg_url: "{{ ripgrep_deb_pkg }}"
  when: ansible_os_family == "Debian"

- name: Install neovim
  become: true
  apt:
    name: neovim
    state: present

- name: Install neovim plugins dependencies
  become: true
  apt:
    name: "{{ nvim_debian_dependencies }}"
    state: present
