---
- name: Add neovim PPA for Ubuntu
  become: true
  apt_repository:
    repo: "ppa:neovim-ppa/unstable"
  register: neovim_ppa
  when: ansible_distribution == "Ubuntu"

- name: Update package list to reflect PPA change
  become: true
  apt:
    update_cache: true
  when:
    - ansible_distribution == "Ubuntu"
    - neovim_ppa is changed

- name: Debian | Install neovim appimage
  include_tasks: "appimage.yml"
  when:
    - ansible_distribution != "Ubuntu"
    - ansible_os_family == "Debian"

- name: Debian | Install ripgrep from github release
  include_role:
    name: "_pkg_install"
    tasks_from: "debian"
  vars:
    pkg_url: "{{ ripgrep_deb_pkg }}"
  when: ansible_os_family == "Debian"

- name: Install neovim
  become: true
  apt:
    name: neovim
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install neovim plugins dependencies
  become: true
  apt:
    name: "{{ nvim_debian_dependencies }}"
    state: present
