---
- include_tasks: osx.yml
  when: ansible_os_family == "Darwin"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Create nvim config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim/"
    state: directory

- name: Create nvim default plugin directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
    state: directory

- name: Copy nvim configuration
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/nvim/"
  loop:
  - init.vim
  - plugins.vim

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"

- name: Create nvim python virtualenv directories
  file:
    path: "{{ nvim_venv_dir }}"
    state: directory

- name: Install neovim python bindings in a dedicated virtualenv
  # NOTE(sheeprine): neovim is used for backward compatibility and will be
  # removed soon.
  pip:
    name: "{{ item[0] }}"
    virtualenv: "{{ nvim_venv_dir }}/{{ item[1] }}"
    virtualenv_python: "{{ item[1] }}"
  loop: "{{ ['pynvim', 'neovim'] | product(['python2', 'python3']) | list }}"
