---
- name: Install neovim
  homebrew:
    name: neovim
    state: head

- name: Install neovim plugins dependencies
  homebrew:
    name: "{{ nvim_osx_dependencies }}"
    state: present

- name: Install universal-ctags
  homebrew:
    name: "universal-ctags/universal-ctags/universal-ctags"
    state: head

- name: Install virtualenv
  pip:
    name: "virtualenv"
    executable: "pip3"
    state: present
