---
- name: Install neovim
  homebrew:
    name: neovim
    state: present

- name: Install neovim plugins dependencies
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
  - git
  - golang
  - python-setuptools
  - python3-setuptools
  - python3-dev
