---
- name: Add tap to click on the trackpad
  osx_defaults:
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1

- name: Disable mouse acceleration for external devices
  osx_defaults:
    domain: .GlobalPreferences
    key: com.apple.mouse.scaling
    type: float
    value: -1

- name: Disable scrollwheel acceleration for external devices
  osx_defaults:
    domain: .GlobalPreferences
    key: com.apple.scrollwheel.scaling
    type: float
    value: -1
