---
- name: Add tap to homebrew
  homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ apps_tap }}"

- name: Install homebrew applications
  homebrew:
    name: "{{ apps_homebrew }}"
    state: present

- name: Install homebrew cask applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ apps_cask }}"
