---
- name: Disable DS_Store on network and USB
  osx_defaults:
    domain: com.apple.desktopservices
    key: "{{ item }}"
    type: bool
    value: true
  loop:
  - "DSDontWriteNetworkStores"
  - "DSDontWriteUSBStores"

- name: Show battery percentage
  osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    value: "YES"
