---
- name: Linux | Install alacritty dependencies
  tags:
  - term
  - term-alacritty
  become: yes
  package:
    name: xclip
    state: present
  when: ansible_system == "Linux"

- name: Debian | Install alacritty from github release
  tags:
    - term
    - term-alacritty
  import_tasks: "../../_pkg_install/tasks/debian.yml"
  vars:
    pkg_url: "{{ alacritty_deb_url }}"
  when: ansible_os_family == "Debian"

- name: Arch Linux | Install alacritty
  tags:
  - term
  - term-alacritty
  become: yes
  package:
    name: alacritty
    state: present
  when: ansible_os_family == "Archlinux"

- name: OSX | Install alacritty
  tags:
    - term
    - term-alacritty
  homebrew_cask:
    name: alacritty
    state: present
  when: ansible_os_family == "Darwin"

- name: Create alacritty config directory
  tags:
    - term
    - term-alacritty
  file:
    path: "{{ ansible_env.HOME }}/.config/alacritty/"
    state: directory

- name: Copy alacritty configuration
  tags:
    - term
    - term-alacritty
  template:
    src: alacritty.j2
    dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"
