---
- name: Debian | Install alacritty dependencies
  become: yes
  apt:
    name: xclip
    state: present
  when: ansible_os_family == "Debian"

- name: Debian | Install alacritty from github release
  include_tasks: "roles/_pkg_install/tasks/debian.yml"
  vars:
    pkg_url: "{{ alacritty_deb_url }}"
  when: ansible_os_family == "Debian"

- name: OSX | Install alacritty
  homebrew:
    name: alacritty
    state: present
  when: ansible_os_family == "Darwin"
