---
- name: Install rxvt on Linux based systems
  include_tasks: rxvt.yml
  when:
  - ansible_os_family != "Darwin"
  - use_rxvt
- name: Install alacritty
  include_tasks: alacritty.yml
  when:
  - use_alacritty

- name: Get path to default terminal emulator
  command: "which {{ default_term }}"
  register: term_path
  check_mode: no
  changed_when: no
  when: ansible_os_family == "Debian"

- name: Set the default terminal emulator
  become: yes
  alternatives:
    name: x-terminal-emulator
    path: "{{ term_path.stdout }}"
  when: ansible_os_family == "Debian"
