---
- name: Ensure rxvt xresources.d directory is present
  tags:
    - term
    - term-rxvt
  file:
    path: "{{ ansible_env.HOME }}/.Xresources.d/rxvt"
    state: directory

- name: Download rxvt colorschemes
  tags:
    - term
    - term-rxvt
  get_url:
    url: "{{ item.1 }}"
    dest: "{{ ansible_env.HOME }}/.Xresources.d/rxvt/{{ item.0 }}"
    force: yes
  loop: "{{ rxvt_themes | dictsort }}"
  # Disable when checking as ansible will not download and trigger a change
  # even if it's not.
  when: not ansible_check_mode

- name: Install rxvt configuration file
  tags:
    - term
    - term-rxvt
  template:
    src: "rxvt.j2"
    dest: "{{ ansible_env.HOME }}/.Xresources.d/rxvt.xresources"
  notify:
    - reload xrdb

- name: Load configuration in Xresources
  tags:
    - term
    - term-rxvt
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.Xresources"
    create: yes
    line: '#include ".Xresources.d/rxvt.xresources"'

- name: Install rxvt
  tags:
    - term
    - term-rxvt
  become: true
  package:
    name: rxvt-unicode
    state: present
