---
- hosts: all
  roles:
  - common
  - nvim
  tasks:
  - include_role:
      name: wm
    when: ansible_os_family == "Debian"
  - include_role:
      name: osx
    when: ansible_os_family == "Darwin"
