---
- hosts: all
  roles:
  - nvim
  - shell
  - tools
  tasks:
  - name: Include window manager tasks
    include_role:
      name: wm
    when: ansible_os_family == "Debian"
  - name: Include OSX related tasks
    include_role:
      name: osx
    when: ansible_os_family == "Darwin"
