---
- hosts: all
  roles:
  - nvim
  - shell
  - term
  - tools
  tasks:
  - name: Include window manager tasks
    import_role:
      name: wm
    tags:
      - wm
    when: ansible_system == "Linux"
  - name: Include OSX related tasks
    include_role:
      name: osx
    when: ansible_os_family == "Darwin"
